import { Document, Page, Text, View } from "@react-pdf/renderer"
import { styles } from "@/components/pdf/styles"
import { formatPaise } from "@/lib/money"

type PurchaseForPdf = {
  id: string
  quantity: number
  pricePerItemPaise: number
  purchaseDate: Date
  vendor: {
    name: string
    address: string | null
    contactNo: string | null
    contactEmail: string | null
  }
  sku: {
    companyName: string
    modelName: string
  }
}

export function PurchaseBillDocument({
  purchase,
}: {
  purchase: PurchaseForPdf
}) {
  const total = purchase.pricePerItemPaise * purchase.quantity

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Purchase Bill</Text>
          <View style={styles.meta}>
            <Text>Bill #{purchase.id.slice(-8).toUpperCase()}</Text>
            <Text>{purchase.purchaseDate.toLocaleDateString("en-IN")}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionLabel}>Vendor</Text>
          <Text style={styles.partyName}>{purchase.vendor.name}</Text>
          {purchase.vendor.address && (
            <Text style={styles.partyLine}>{purchase.vendor.address}</Text>
          )}
          {purchase.vendor.contactNo && (
            <Text style={styles.partyLine}>{purchase.vendor.contactNo}</Text>
          )}
          {purchase.vendor.contactEmail && (
            <Text style={styles.partyLine}>{purchase.vendor.contactEmail}</Text>
          )}
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeaderRow}>
            <Text style={styles.colItem}>Item</Text>
            <Text style={styles.colQty}>Qty</Text>
            <Text style={styles.colPrice}>Price/item</Text>
            <Text style={styles.colTotal}>Total</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.colItem}>
              {purchase.sku.companyName} — {purchase.sku.modelName}
            </Text>
            <Text style={styles.colQty}>{purchase.quantity}</Text>
            <Text style={styles.colPrice}>
              {formatPaise(purchase.pricePerItemPaise)}
            </Text>
            <Text style={styles.colTotal}>{formatPaise(total)}</Text>
          </View>
        </View>

        <View style={styles.totalsBlock}>
          <View style={styles.totalRow}>
            <Text>Total</Text>
            <Text>{formatPaise(total)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>Generated by Inventory Dashboard</Text>
      </Page>
    </Document>
  )
}
