import { Document, Page, Text, View } from "@react-pdf/renderer"
import { styles } from "@/components/pdf/styles"
import { formatPaise } from "@/lib/money"

type SaleForPdf = {
  id: string
  quantity: number
  pricePerItemPaise: number
  saleDate: Date
  client: {
    name: string
    address: string | null
    contactNo: string | null
    contactEmail: string | null
  }
  sku: {
    companyName: string
    modelName: string
  }
}

export function SalesInvoiceDocument({ sale }: { sale: SaleForPdf }) {
  const total = sale.pricePerItemPaise * sale.quantity

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Invoice</Text>
          <View style={styles.meta}>
            <Text>Invoice #{sale.id.slice(-8).toUpperCase()}</Text>
            <Text>{sale.saleDate.toLocaleDateString("en-IN")}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionLabel}>Bill To</Text>
          <Text style={styles.partyName}>{sale.client.name}</Text>
          {sale.client.address && (
            <Text style={styles.partyLine}>{sale.client.address}</Text>
          )}
          {sale.client.contactNo && (
            <Text style={styles.partyLine}>{sale.client.contactNo}</Text>
          )}
          {sale.client.contactEmail && (
            <Text style={styles.partyLine}>{sale.client.contactEmail}</Text>
          )}
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeaderRow}>
            <Text style={styles.colItem}>Item</Text>
            <Text style={styles.colQty}>Qty</Text>
            <Text style={styles.colPrice}>Price/item</Text>
            <Text style={styles.colTotal}>Total</Text>
          </View>
          <View style={styles.tableRow}>
            <Text style={styles.colItem}>
              {sale.sku.companyName} — {sale.sku.modelName}
            </Text>
            <Text style={styles.colQty}>{sale.quantity}</Text>
            <Text style={styles.colPrice}>
              {formatPaise(sale.pricePerItemPaise)}
            </Text>
            <Text style={styles.colTotal}>{formatPaise(total)}</Text>
          </View>
        </View>

        <View style={styles.totalsBlock}>
          <View style={styles.totalRow}>
            <Text>Total</Text>
            <Text>{formatPaise(total)}</Text>
          </View>
        </View>

        <Text style={styles.footer}>Generated by Inventory Dashboard</Text>
      </Page>
    </Document>
  )
}
